#!/bin/zsh
DEPENDENCIES+=(jq)
REQUIRED_ENV+=(AWS__EFS__LOCAL_MOUNT_POINT)

use cloud/aws/cli
#####################################################################

MAIN() {
	[ ! -d "$AWS__EFS__LOCAL_MOUNT_POINT" ] && {
		echo.status 'no efs currently mounted'
		exit 0
	}

	local MOUNTED=$(ls "$AWS__EFS__LOCAL_MOUNT_POINT")
	[ ! $MOUNTED ] && {
		echo.status 'no efs currently mounted'
		exit 0
	}

	GETSUDO || exit 1


	local SELECTED=$(echo $MOUNTED | FZF 'select a file system to unmount')
	[ ! $SELECTED ] && ABORT

	local EFS="$AWS__EFS__LOCAL_MOUNT_POINT/$SELECTED"
	echo.status "unmounting '$SELECTED'"
	sudo umount $EFS >/dev/null 2>&1
	sudo rmdir $EFS \
		&& echo.success "done" \
		|| FAIL 2 "failed to unmount '$EFS'"
}
