#!/bin/zsh
_DEPENDENCIES+=()
_REQUIRED_ENV+=()
source ${0:a:h}/common.zsh
#####################################################################

__STATUS "performing AWS ECR docker login"

_AWS ecr get-login-password | docker login \
	--username AWS \
	--password-stdin \
	"$AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com" \
	&& __SUCCESS "logged in to 'AWS:$AWS_ACCOUNT:$AWS_REGION'" \
	|| __FAIL 1 "unable to login to '$AWS_ACCOUNT' in '$AWS_REGION'"
