#!/bin/zsh
DEPENDENCIES+=(docker)
#####################################################################

MAIN() {
	echo.warning 'this will prune all docker resources from the current machine'
	echo.warning 'pruned resources are PERMANENTLY DELETED'
	yN 'continue?' || return 1

	echo.success "CONTAINER : $(docker container prune -f 2>/dev/null | tail -n 1)"
	echo.success "IMAGE     : $(docker image prune -f 2>/dev/null | tail -n 1)"
	echo.success "VOLUME    : $(docker volume prune -f 2>/dev/null | tail -n 1)"
}
