#!/bin/zsh
DEPENDENCIES+=()
REQUIRED_ENV+=()

use cloud/aws/rds
use db/postgres

CHECK_ENVIRONMENT
#####################################################################

LOAD_BACKUP() {
	local DB_HOST DB_PORT DB_NAME DB_USER DB_PASS
	RDS__GET_DATABASE_CREDENTIALS $@ || return 1

	PG_RESTORE
}


#####################################################################
LOAD_BACKUP $@
