#!/bin/zsh
use system/vim/vundle
#####################################################################

MAIN() {
	[ -d "$HOME/.vim/bundle/Vundle.vim" ] || {
		mkdir -p "$HOME/.vim/bundle/"
		git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
	}

	VUNDLE__PLUGIN_INSTALL  || return 1
	VUNDLE__REBUILD_PLUGINS || return 2
}
