#!/usr/bin/env zsh
DEPENDENCIES+=(tic)

use system/config
#####################################################################

MAIN() {
	[ ! $TERMINFO_PATH ] && return 0
	[ ! -d $TERMINFO_PATH ] && utils.fail 1 "TERMINFO_PATH='$TERMINFO_PATH' does not exist"

	local ERRORS=0
	for TERMINFO_FILE in $(find $TERMINFO_PATH -type f)
	do
		tic -x $TERMINFO_FILE >/dev/null 2>&1 \
			&& echo.success "added '$(basename $TERMINFO_FILE)'" \
			|| echo.error "failed to add '$(basename $TERMINFO_FILE)'" \
			;
	done

	utils.check-errors
}
