#!/usr/bin/env zsh
use scwrypts/meta
#####################################################################

MAIN() {
	echo.status 'updating all config files and links'
	scwrypts.meta.run --name system/config/symlinks --group scwrypts --type zsh || exit 1
	scwrypts.meta.run --name system/config/terminfo --group scwrypts --type zsh || exit 2
	echo.success 'finished updating config files and links'
}
