#!/bin/zsh
use office/memo
#####################################################################

MAIN() {
	local MEMO_NAME=$(MEMO__LIST_ALL | FZF 'select a memo to delete')
	local MEMO_FILE="$MEMO__DIR/$MEMO_NAME.$MEMO__FILETYPE"
	[ "$MEMO_NAME" ] && [ -f "$MEMO_FILE" ] || ABORT

	echo.status "--- START OF MEMO ---------------------------------------------------"
	cat "$MEMO_FILE"
	echo.status "--- END OF MEMO -----------------------------------------------------"

	echo.warning '
		memos are not backed up by default; deletion is permanent!
	'

	yN 'are you sure you want to delete this memo?' || ABORT

	echo.status "deleting memo '$MEMO_FILE'"
	rm "$MEMO_FILE" \
		&& echo.success "removed memo '$MEMO_NAME'" \
		|| FAIL 1 "failed to remove memo '$MEMO_NAME'" \
		;
}
