#!/usr/bin/env zsh
use scwrypts/virtualenv/update
use scwrypts/virtualenv/delete
#####################################################################

USAGE__options='
	-g, --group   name of group with specialized virtualenv (default "scwrypts")
	-t, --type    type of virtual environment to refresh
	'

USAGE__description='
	drops, recreates, and updates the virtual environment used
	by scwrypts in the appropriate group
	'

#####################################################################

MAIN() {
	local ENV_GROUP ENV_TYPE

	local ERRORS=0 _S
	while [[ $# -gt 0 ]]
	do
		_S=1
		case $1 in
			-g | --group )
				[ $2 ] && ((_S+=1)) \
					|| echo.error "missing group name" \
					|| break

				ENV_GROUP="$2"
				;; 

			-t | --type  )
				[ $2 ] && ((_S+=1)) \
					|| echo.error "missing env type" \
					|| break

				ENV_TYPE="$2"
				;;
		esac
		shift $_S
	done
	
	[ $ENV_GROUP ] || ENV_GROUP=scwrypts

	[ $ENV_TYPE ] || ENV_TYPE=$(\
		echo ${SCWRYPTS_VIRTUALENV__AVAILABLE_VIRTUALENVS[@]} \
			| sed 's/ \+/\n/' \
			| utils.fzf 'select an environment to refresh' \
		)
	[ $ENV_TYPE ] || echo.error "no environment type selected"

	utils.check-errors

	##########################################
	: \
		&& DELETE_VIRTUALENV "$ENV_GROUP" "$ENV_TYPE" \
		&& UPDATE_VIRTUALENV "$ENV_GROUP" "$ENV_TYPE" \
		;
}
