#!/bin/zsh
DEPENDENCIES+=()
REQUIRED_ENV+=()

use scwrypts/virtualenv

CHECK_ENVIRONMENT
#####################################################################

while [[ $# -gt 0 ]]
do
	case $1 in
		-g | --group ) ENV_GROUP="$2"; shift 1 ;; 
	esac
	shift 1
done

[ ! $ENV_GROUP ] && ENV_GROUP=scwrypts

ENV_TYPE=$(echo $AVAILABLE_VIRTUALENVS | sed 's/ \+/\n/' | FZF 'select an environment to refresh')
[ ! $ENV_TYPE ] && ABORT

REMINDER "
	this will permanently remove all artifacts for the scwrypts $ENV_TYPE environment
	(safe unless you have put something important in $(GET_VIRTUALENV_PATH $ENV_GROUP $ENV_TYPE))
	"

Yn "drop and recreate $ENV_TYPE virtual environment?" || ABORT

REFRESH_VIRTUALENV $ENV_GROUP $ENV_TYPE
