#!/usr/bin/env zsh
use scwrypts/virtualenv/update
#####################################################################

MAIN() {
	local ERRORS=0
	local ENV_TYPE ENV_TYPE_COUNT=${#SCWRYPTS_VIRTUALENV__AVAILABLE_VIRTUALENVS[@]}

	echo.status 'beginning update for all environments'
	for ENV_TYPE in ${SCWRYPTS_VIRTUALENV__AVAILABLE_VIRTUALENVS[@]}
	do
		scwrypts.virtualenv.update $ENV_TYPE \
			&& echo.success "successfully updated '${ENV_TYPE}'" \
			|| echo.error   "error updating '${ENV_TYPE}'" \
			;
	done

	[[ ${ERRORS} -eq 0 ]] \
		&& echo.success "successfully updated ${ENV_TYPE_COUNT} / ${ENV_TYPE_COUNT} environment(s)" \
		|| echo.error   "failed to update ${FAILED_COUNT} / ${ENV_TYPE_COUNT} environment(s)" \
		;
}
