#!/bin/zsh
use scwrypts/virtualenv
#####################################################################

MAIN() {
	STATUS 'beginning update for all environments'
	
	FAILED_COUNT=0
	
	for ENV_GROUP in ${SCWRYPTS_GROUPS[@]}
	do
		for ENV_TYPE in ${AVAILABLE_VIRTUALENVS[@]}
		do
			UPDATE_VIRTUALENV $ENV_GROUP $ENV_TYPE || ((FAILED_COUNT+=1))
		done
	done
	
	[[ $FAILED_COUNT -eq 0 ]] \
		&& SUCCESS 'all environments up-to-date' \
		|| FAIL $FAILED_COUNT "failed to update $FAILED_COUNT more environment(s)"
}
