#!/usr/bin/env zsh
#####################################################################

USAGE__options='
	-e, --exit-code         desired exit code of the function (default "0")
	-f, --output-function   one of the zsh/utils output functions (default "success")
	-m, --message           a message to display (default "Hello, World!")
'

USAGE__description='
	a simple hello-world-style script which allows specific scwrypts
	conditions to be quickly emulated
'

#####################################################################

MAIN() {
	local OUTPUT_FUNCTION=success
	local EXIT_CODE=0
	local MESSAGE='Hello, world!'

	eval "${ZSHPARSEARGS}"

	##########################################

	[[ ${OUTPUT_FUNCTION} =~ ^fail$ ]] && utils.fail ${EXIT_CODE} "${MESSAGE}"

	echo.${OUTPUT_FUNCTION} "${MESSAGE}"
	return ${EXIT_CODE}
}

#####################################################################

MAIN.parse() {
	local PARSED=0

	case $1 in
		-e | --exit-code )
			PARSED=2
			EXIT_CODE="$2"
			;;
		-f | --output-function )
			PARSED=2
			OUTPUT_FUNCTION="$2"
			;;
		-m | --message )
			PARSED=2
			MESSAGE="$2"
			;;
	esac

	return ${PARSED}
}
