#!/bin/zsh
#####################################################################

MAIN() {
	local USAGE__description='
		a simple hello-world-style script which allows specific scwrypts
		conditions to be quickly emulated
	'

	local USAGE__args='
		$@   paths or lookup patterns to test
	'

	local \
		ARGS=() ARGS_FORCE=disabled \
		PARSERS=()

	eval "$ZSHPARSEARGS"

	##########################################
	
	local MODE
	[[ ${#ARGS[@]} -eq 0 ]] \
		&& MODE=all \
		|| MODE=filter \
		;
	
	local TEST_FILES=() GROUP GROUP_ROOT FIND_ARGS=() FILTER
	for GROUP in ${SCWRYPTS_GROUPS[@]}
	do
		FIND_ARGS=(-type f -name \*.test.zsh)

		GROUP_ROOT="$(eval echo '$SCWRYPTS_ROOT__'$GROUP)"

		for FILTER in ${ARGS[@]}
		do
			FIND_ARGS+=(-a -name \*$FILTER\*)
		done

		TEST_FILES+=($(find "$GROUP_ROOT" ${FIND_ARGS[@]}))
	done

	local SCWRYPTS_CONFIG="$(scwrypts --config)"
	local TEST_FILE
	for TEST_FILE in ${TEST_FILES[@]}
	do
		zsh <<< "
		$SCWRYPTS_CONFIG
		source '$TEST_FILE'
		use test
		CHECK_ENVIRONMENT
		SCWRYPTS__EXECUTE_ALL_TESTS
		"
	done
}

#####################################################################
