#!/usr/bin/env zsh
#####################################################################

use scwrypts/template/module/create

#####################################################################

scwrypts.template.module.create.parse.usage

MAIN() { scwrypts.template.module.create $@; }
