#!/bin/zsh               
DEPENDENCIES+=()
REQUIRED_ENV+=()

use scwrypts/environment-files

CHECK_ENVIRONMENT
#####################################################################

PROMPT 'choose an environment to delete'
ENV_NAME=$(SCWRYPTS__SELECT_ENV)
[ ! $ENV_NAME ] && ABORT

ENV_FILE=$(SCWRYPTS__GET_ENV_FILE $ENV_NAME)

STATUS "preparing to remove '$ENV_NAME'"

WARNING "
	the '$ENV_NAME' environment will be removed
	configured options and stored credentials will be lost forever
 "

yN 'continue?' || ABORT

STATUS "removing environment"
rm "$ENV_FILE" \
	&& SUCCESS "removed '$ENV_NAME'" \
	|| FAIL 3 "unable to remove '$ENV_FILE'; is it protected?"
