#!/bin/zsh               
DEPENDENCIES+=()
REQUIRED_ENV+=()

use scwrypts/environment-files

CHECK_ENVIRONMENT
#####################################################################

[ $1 ] && ENV_NAME="$1"

[ ! $1 ] && {
	[ $SCWRYPTS_ENV ] \
		&& ENV_NAME=$SCWRYPTS_ENV \
		|| ENV_NAME=$(SCWRYPTS__SELECT_OR_CREATE_ENV)
}
[ ! $ENV_NAME ] && ABORT

ENV_FILE=$(SCWRYPTS__GET_ENV_FILE $ENV_NAME 2>/dev/null)
[ ! -f "$ENV_FILE" ] && {
	STATUS "Creating '$ENV_NAME'..." \
		&& touch "$ENV_FILE" \
		&& SCWRYPTS__RUN --name scwrypts/environment/synchronize --group scwrypts --type zsh -- --no-prompt \
		&& SUCCESS "created '$ENV_NAME'" \
		|| { ERROR "failed to create '$ENV_FILE'"; exit 1; }
}

EDIT $ENV_FILE

SCWRYPTS__RUN --name scwrypts/environment/synchronize --group scwrypts --type zsh -- --no-prompt \
	|| FAIL 4 'failed to run environment sync' \
	;

SUCCESS "environment '$ENV_NAME' successfully modified"
