#!/bin/zsh
source ${0:a:h}/common.zsh
__CHECK_IMPORTS
#####################################################################

__PULL_ALL_MEDIA() {
	local FLAGS=($@)
	local FAILED_COUNT=0

	__STATUS 'starting media download from s3'

	local TARGET
	for TARGET in $AWS__S3__MEDIA_TARGETS
	do
		__SYNC_MEDIA pull $TARGET $FLAGS || ((FAILED_COUNT+=1))
	done

	[[ $FAILED_COUNT -eq 0 ]] \
		&& __SUCCESS 'local media files now up-to-date' \
		|| __FAIL $FAILED_COUNT 'unable to download one or more targets' \
		;
}

#####################################################################

__PULL_ALL_MEDIA $@
