#!/bin/zsh               
#####################################################################

MAIN() {
	cd $SCWRYPTS_ROOT
	
	echo.status "Found $(ls $SCWRYPTS_LOG_PATH | wc -l) log files"
	echo.warning "
		this will permanently clear all local cloud script logs found in
		'$SCWRYPTS_LOG_PATH'
	"
	
	yN 'continue?' || ABORT
	
	echo.status 'removing logfiles'
	rm -rf $SCWRYPTS_LOG_PATH/* \
		&& echo.success 'done' \
		|| { echo.error 'failed :c'; exit 2; }\
		;
}
