#!/bin/zsh               
#####################################################################

MAIN() {
	cd $SCWRYPTS_ROOT
	PROMPT 'select a script log'
	LOG_FILE=$(ls -t $SCWRYPTS_LOG_PATH | FZF 'logfile')
	[ ! $LOG_FILE ] && { echo.error 'user abort'; exit 1; }
	
	echo.status 'opening logfile'
	LESS "$SCWRYPTS_LOG_PATH/$LOG_FILE"
	echo.success 'done'
}
