#!/bin/zsh
_DEPENDENCIES+=()
_REQUIRED_ENV+=()
source ${0:a:h}/common.zsh
#####################################################################

PLUGIN_INSTALL() {
	VUNDLE_PLUGIN_INSTALL || return 1
	VUNDLE_REBUILD_PLUGINS || return 2
}

#####################################################################
PLUGIN_INSTALL $@
